name: xab

services:
    app: 
      build:           
        context: .
        dockerfile: ./nginx/Dockerfile
      ports: 
        - "80:80"
      volumes:
        - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/logs:/etc/nginx/logs
      healthcheck:
        test: ["CMD", "nc", "-z", "localhost", "80"]
        interval: 2s
        timeout: 2s
        retries: 100
        start_period: 10s        
      networks:
        default:  

networks:
  default: