name: xab

services:
    webserver: 
      build:           
        context: .
        dockerfile: ./nginx/Dockerfile
      ports: 
        - "80:80"
      volumes:
        - ./nginx/logs:/etc/nginx/logs
      healthcheck:
        test: ["CMD", "nc", "-z", "localhost", "80"]
        interval: 2s
        timeout: 2s
        retries: 100
        start_period: 10s        
      networks:
        default: 

    postgres-db:
      image: postgres:16.0-alpine
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: example
        PGDATA: /data
        POSTGRES_INITDB_ARGS: "--username=postgres"
      volumes:
        - ./db/postgresql/data:/data   
      healthcheck:
        test: "pg_isready -q -h localhost -p 5432 -U postgres -d postgres || exit 1"
        interval: 10s
        timeout: 10s
        retries: 3
        start_period: 10s     
      restart: always        

    adminer:
      image: adminer
      ports:
        - 8080:8080
      environment:    
        ADMINER_DEFAULT_SERVER: postgres-db
      restart: always       

    myapp: 
      build:
        context: .
        dockerfile: ./app/Dockerfile
      ports: 
        - "3000:3000"
      healthcheck:
        test: ["CMD", "nc", "-z", "localhost", "3000"]
        interval: 2s
        timeout: 2s
        retries: 100
        start_period: 10s     
      networks:
        default:  

    welcome:
      image: rancher/cowsay:latest
      command: "-W 45 \"Test site:http://localhost:3000\nAdminer:http://localhost:8080\""
      depends_on:
        webserver:
          condition: service_healthy
        adminer:
          condition: service_started
        postgres-db:
          condition: service_healthy
        myapp:
          condition: service_healthy        

networks:
  default: